import streamlit as st
import asyncio
import os
from teams.investment_team import get_investment_team

st.set_page_config(page_title="Stock Investment Analyst", layout="wide", page_icon="📈")

# ------------------------------------------------------------------------------
# OpenTelemetry Setup
# ------------------------------------------------------------------------------
from opentelemetry import trace
# from opentelemetry.exporter.otlp.proto.grpc.trace_exporter import OTLPSpanExporter
from opentelemetry.exporter.otlp.proto.http.trace_exporter import OTLPSpanExporter
from opentelemetry.instrumentation.openai import OpenAIInstrumentor
from opentelemetry.sdk.resources import Resource
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import BatchSpanProcessor

otel_endpoint = os.getenv("OTEL_EXPORTER_OTLP_ENDPOINT")

if otel_endpoint:
    enable_otel = True
else:
    otel_endpoint = "https://myotel.azurewebsites.net/v1/traces"
    enable_otel = True

if enable_otel:
    try:
        # Set up telemetry span exporter.
        # otel_exporter = OTLPSpanExporter(endpoint=otel_endpoint, insecure=True)
        otel_exporter = OTLPSpanExporter(endpoint=otel_endpoint)
        span_processor = BatchSpanProcessor(otel_exporter)

        # Set up telemetry trace provider.
        tracer_provider = TracerProvider(resource=Resource({"service.name": "stock-analyst"}))
        tracer_provider.add_span_processor(span_processor)
        trace.set_tracer_provider(tracer_provider)

        # Instrument the OpenAI Python library
        OpenAIInstrumentor().instrument()
        print(f"OpenTelemetry enabled with endpoint: {otel_endpoint}")
    except Exception as e:
        print(f"Failed to initialize OpenTelemetry: {e}")
else:
    print("OpenTelemetry disabled (Running in HF Space with no configured endpoint).")

# Get a tracer (works even if OTEL is disabled, returning a NoOp tracer)
tracer = trace.get_tracer("stock-analyst")

# ------------------------------------------------------------------------------
# Custom CSS for layout improvements
# ------------------------------------------------------------------------------
st.markdown("""
    <style>
        .block-container {
            padding-top: 1.5rem;
            padding-bottom: 3rem;
        }
    </style>
""", unsafe_allow_html=True)

# ------------------------------------------------------------------------------
# Main Content
# ------------------------------------------------------------------------------
st.title("📈 Stock Investment Analyst")

# IMPORTANT DISCLAIMER
st.warning(
    "**⚠️ DISCLAIMER: EDUCATIONAL PURPOSE ONLY**\n\n"
    "This tool is an AI-powered experiment designed for educational and demonstration purposes. "
    "The analysis provided is generated by artificial intelligence and **DOES NOT** constitute financial, investment, or legal advice. "
    "Do not use this tool to make real-world financial decisions. Always consult with a qualified financial advisor."
)

st.markdown("#### Get a comprehensive analysis from our AI team of agents.")

# Input section with better spacing
st.divider()
with st.container():
    col1, col2 = st.columns([3, 1], gap="medium")
    with col1:
        stock_name = st.text_input(
            "Enter Stock Ticker", 
            value="Tesla", 
            placeholder="e.g. NVDA, TSLA, AAPL",
            help="Enter the ticker symbol of the company you want to analyze."
        )
    with col2:
        # Align button with input box
        st.write("") # Spacer
        st.write("") # Spacer
        analyze_btn = st.button("🔍 Analyze Stock", type="primary", use_container_width=True)
st.divider()

async def run_analysis(ticker):
    # Start a span for the analysis task. 
    # This becomes the parent for all subsequent spans (like OpenAI calls).
    with tracer.start_as_current_span("run_analysis") as span:
        span.set_attribute("stock.ticker", ticker) # Add useful metadata
        
        task = f"Analyze stock trends, news, and sentiment for {ticker}, plus analyst reports and expert opinions, and then decide whether to invest."
        
        st.markdown(f"### Analysis for **{ticker}**")
        
        # Container for live updates
        chat_container = st.container()
        
        try:
            # Run the team stream
            investment_team = get_investment_team()
            stream = investment_team.run_stream(task=task)
            
            # Define icons for each agent
            AGENT_ICONS = {
                "stock_trends_agent": "📈",
                "news_agent": "📰",
                "sentiment_agent": "💡",
                "decision_agent": "⚖️",
                "user": "👤",
                "System": "⚙️"
            }
            
            async for message in stream:
                # Check if message has source and content attributes typical of agent messages
                source = getattr(message, 'source', 'System')
                
                with chat_container:
                    if 'TaskResult' in message.__class__.__name__:
                        if hasattr(message, 'stop_reason') and message.stop_reason:
                             st.info(f"Analysis Completed: {message.stop_reason}")
                        continue
    
                    # Use the icon mapping, default to None (Streamlit default) if not found
                    avatar = AGENT_ICONS.get(source, None)
                    
                    with st.chat_message(source, avatar=avatar):
                        # Handle Tool Call events specifically to make them look like system logs
                        if 'ToolCall' in message.__class__.__name__:
                            with st.expander(f"⚙️ Tool Usage: {source}", expanded=False):
                                st.write(message)
                            continue
    
                        content = getattr(message, 'content', "")
                        st.write(content)
                        
        except Exception as e:
            # Record the exception in the span if something crashes
            span.record_exception(e)
            span.set_status(trace.Status(trace.StatusCode.ERROR))
            st.error(f"An error occurred during analysis: {e}")

if analyze_btn:
    if stock_name:
        with st.spinner(f"Gathering data and analyzing {stock_name}..."):
            # Create a new event loop for this run if needed, or simply run
            asyncio.run(run_analysis(stock_name))
    else:
        st.warning("Please enter a valid stock ticker.")
